name: .NET
env:
  registryName: devowghdevopsreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}

on:
  push:
    paths:
      - 'Application/**'
  pull_request:
    paths:
      - 'Application/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Application/src/RazorPagesTestSample/
    - name: Build
      run: dotnet build ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore
    - name: Test
      run: dotnet test ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj --no-build --verbosity normal
  
  docker-build-push:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        uses: Azure/docker-login@v1
        with:
          login-server: devowghdevopsreg.azurecr.io
          username: ${{secrets.AZURE_ACR_USR}}
          password: ${{secrets.AZURE_ACR_PSDD}}
      - name: Docker build
        run: docker build $dockerFolderPath --tag $registryName/$repositoryName:$tag --build-arg build_version=$tag 
      - run: cat ${{ env.DOCKER_CONFIG }}/config.json
      - name: Docker push
        run: docker push $registryName/$repositoryName:$tag
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'devowghdevops-dev'
          publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE }}
          images: '$registryName/$repositoryName:$tag'
  
##  publish-to-webapp:
##     needs: docker-build-push
##     runs-on: ubuntu-latest
##     steps:
##     - name: Checkout
##       uses: actions/checkout@v2
##     - name: Azure Login
##       uses: azure/login@v1
##       with:
##         creds: ${{ secrets.AZURE_CREDENTIALS }}
##     - name: Deploy to WebApp
##       uses: azure/webapps-deploy@v2
##       with:
##         app-name: 'devowghdevops-dev'
##         publish-profile: dotnetcore
##         images: '$registryName/$repositoryName:$tag'
     

